@startuml Architecture Design
    !theme blueprint
    title Architecture Design

    package TicTacToe{
        package ConsoleApp{
            namespace Models #Green{}
            namespace Types #OrangeRed{}
            namespace Enums #SaddleBrown{}
            namespace ConsoleIOs #SeaGreen {
            }
            ConsoleIOs ..> IO

            Models ..> Enums
            Models ..> Types
            Models ..> ConsoleIOs

            Types ..> Enums
            Types..> ConsoleIOs

            Enums ..> ConsoleIOs

            
        }
    }
    TicTacToe ..> System

    package System{
    }
    
    package IO{
    }
    IO ..> System
@enduml

@startuml Use Case Design ConfigurePlayer
    !theme blueprint
    allow_mixing
    title Use Case Design - ConfigurePlayer
    
    actor "Player" as User
    
    package Models{
        object ":TicTacToe" as TicTacToe{
        }    
        object ":PlayerConfiguration" as PlayerConfiguration{
        }        
        object ":Player" as Player{
        }    
    }

    package Enums{
        object ":Message" as Message{
        }    
        object ":Error" as Error{
        }    
        object ":Token" as Token{
        }    
    }

    package ConsoleIOs{                
        object ":ConsoleIO" as ConsoleIO{
        }    
    }

    User --> TicTacToe : ConfigurePlayer()
        TicTacToe --> PlayerConfiguration : ConfigurePlayer()
            PlayerConfiguration --> Message : GetMessage()
            PlayerConfiguration --> ConsoleIO : ReadInt(Message)
            PlayerConfiguration --> Error : IsNull() \nWriteLine()
                Error --> ConsoleIO : WriteLine(ErrorMessage)
            PlayerConfiguration --> Token : GetTokens()
            PlayerConfiguration --> Player : Create(Token)

@enduml

@startuml Use Case Design Start
    !theme blueprint
    allow_mixing
    title Use Case Design - Start
    
    actor "Player" as User
    
    package Models{
        object ":TicTacToe" as TicTacToe{
        }
        object ":Board" as Board{
        }    
        object ":Player" as Player{
        }    
    }

    package Enums{
        object ":Message" as Message{
        }    
        object ":Token" as Token{
        }    
    }

    package Types{                
        object ":Coordinte" as Coordinte{
        }    
    }

    package ConsoleIOs{                
        object ":ConsoleIO" as ConsoleIO{
        }    
    }

    User --> TicTacToe : Start()
        TicTacToe --> Board : NewGame()
            Board --> Message
                note on link
                    HorizontalLine.WriteLine()
                    VerticalLine.Write()
                endnote
            Board --> Coordinte : GetCoordinate(i,j)
            Board --> Token : Write()
            Board --> ConsoleIO : WriteLine()
        TicTacToe --> Player : NewGame()
@enduml

@startuml Use Case Design Play
    !theme blueprint
    allow_mixing
    title Use Case Design - Play
    
    actor "Player" as User
    
    package Models{
        object ":TicTacToe" as TicTacToe{
        }
        object ":Board" as Board{
        }    
        object ":Turn" as Turn{
        }   
        object ":Player" as Player{
        }    
    }

    package Enums{
        object ":Message" as Message{
        }    
        object ":Token" as Token{
        }    
        object ":Error" as Error{
        }    
    }

    package Types{                
        object ":Coordinte" as Coordinte{
        }               
        object ":ClosedInterval" as ClosedInterval{
        }    
    }

    package ConsoleIOs{                
        object ":ConsoleIO" as ConsoleIO{
        }    
    }

    User --> TicTacToe : Play()
        TicTacToe --> Turn : GetCurrent()\nChange()
            Turn --> Player : GetPlayer()
        TicTacToe --> Message : WriteLine(player)
            Message --> ConsoleIO : WriteLine(player)
        TicTacToe --> Player 
            note on link
                HasToken()
                PutToken()
                MoveToken()
                WriteWinnerMessage()
            endnote
            Player --> Message : GetMessage(EnterCoordinate)\nGetMessage(EnterOriginCoordinateToMove)\nGetMessage(EnterTargetCoordinateToPut)
            Player --> Coordinte : Read(Message)
                Coordinte --> Message : GetRow()\nGetColunm()
                Coordinte --> ConsoleIO : ReadInt(row)\nReadInt(colunm)
                Coordinte --> ClosedInterval : IsValir(row)\nIsValir(colunm)
                Coordinte --> Error : IsNull(Error)\nWriteLine(ErrorMessage)
            Player --> Token : GetToken()
            Player --> Board 
                note on link
                    PutToken(target, token)
                    IsEmpty(target, token)
                    MoveToken(origin, target)
                    IsOccupied(Coordinate, Token)
                endnote
            Player --> Error : IsNull()\nError.WriteLine()
                Error --> ConsoleIO : WriteLine(Error)
        TicTacToe --> Board : IsWinner()
@enduml

@startuml Use Case Design Resume
    !theme blueprint
    allow_mixing
    title Use Case Design - Resume
    
    actor "Player" as User
    
    package Models{
        object ":TicTacToe" as TicTacToe{
        }
        object ":Turn" as Turn{
        }   
        object ":Player" as Player{
        }    
    }

    package Enums{
        object ":Message" as Message{
        }    
    }

    package ConsoleIOs{                
        object ":ConsoleIO" as ConsoleIO{
        }             
        object ":YesNotDialog" as YesNotDialog{
        }    
    }

    User --> TicTacToe : IsResume()
        TicTacToe --> Turn : GetCurrent()
            Turn --> Player : GetPlayer()
        TicTacToe --> Player : IsContinue()
            Player --> Message : GetMessage(Resume)
            Player --> YesNotDialog : Read(Message)\nIsAffirmative()
                YesNotDialog --> ConsoleIO : ReadChar(Message)

@enduml

@startuml Design Class Models
    !theme blueprint
    title Design Class - Models

    package TicTacToe{
        package ConsoleApp{  
            namespace Models{
                class TicTacToe{
                    ~TicTacToe()
                    ~Run()
                    -ConfigurePlayer(Board)
                    -Start()
                    -Play()
                    -IsResume() : boolean
                }
                TicTacToe *--> Board
                TicTacToe *--> Turn
                TicTacToe *--> "2" Player
                TicTacToe ..> PlayerConfiguration

                class Board{
                    ~Board()
                    ~Reset()
                    -GetToken(Coordinate)
                    ~PutToken(Coordinate, Token)
                    ~MoveToken(Origin, Target)
                    ~IsTicTacToe(Token) : boolean
                    ~IsEmpty(Coordinate) : boolean
                    ~IsOccupied(Coordinate, Token) : boolean
                }

                class Turn{
                    -{static}MaxPlayers
                    -current : int
                    ~Turn(Players)
                    +Change()
                    +GetCurrent() : Player
                }
                Turn --> "2" Player 

                class Player{
                    -tokens : int
                    ~Player(Board, Token)
                    ~GetToken() : Token
                    ~HasToken() : boolean
                    ~PutToken()
                    ~GetCoordinate(Message) : Coordinate
                    ~CheckErrorToPut(Coordinate) : Error
                    ~MoveToken()
                    ~CheckOriginErrorToMove(origin) : Error
                    ~CheckTargetErrorToMove(origin, target) : Error
                    ~WriteWinner()
                }
                Player --> Board

                class PlayerConfiguration{
                    ~PlayerConfiguration()
                    ~ConfigurePlayer(Board) : Players
                }
                PlayerConfiguration ..> "2" Player
                PlayerConfiguration ..> Board
            }

            namespace Types{
                class Coordinate{
                }
                Coordinate <.up. Models.Board
                Coordinate <.up. Models.Player
            }

            namespace Enums{
                enum Message{
                }
                Message <.up. Models.Player

                enum Token{
                }
                Token <.up. Models.Board
                Token <.up. Models.Player
                Token <.up. Models.PlayerConfiguration

                enum Error{
                }
                Error <.up. Models.Player
            }

            namespace ConsoleIOs{
                class ConsoleIO{
                }
                ConsoleIO <.up. Models.Player
                ConsoleIO <.up. Models.PlayerConfiguration

                class YesNotDialog{
                }
                YesNotDialog <.up. Models.Player
            }
        }
    }
@enduml

@startuml Design Class Types
    !theme blueprint
    title Design Class - Types

    package TicTacToe{
        package ConsoleApp{  
            namespace Types{
                class Coordinate{
                    ~{static}Dimension
                    -row : int
                    -colunm : int
                    ~Coordinate()
                    ~Coordinate(row, colunm)
                    ~GetRow() : int
                    ~GetColunm() : int
                    ~Read()
                    ~ReadRamdon()
                    ~IsValid()
                }
                Coordinate ..> ClosedInterval
                
                class ClosedInterval{
                    -min : int
                    -max : int
                    ~ClosedInterval(min, max)
                    ~IsValid(value) : boolean
                }
            }

            namespace Enums{
                enum Message{
                }
                Message <.up. Types.Coordinate

                enum Error{
                }
                Error <.up. Types.Coordinate
            }

            namespace ConsoleIOs{
                class ConsoleIO{
                }
                ConsoleIO <.up. Types.Coordinate
            }
        }
    }
@enduml

@startuml Design Class Enums
    !theme blueprint
    title Design Class - Enums

    package TicTacToe{
        package ConsoleApp{  

            namespace Enums{
                enum Message{
                    +TicTacToe
                    +HorizontalLine
                    +VerticalLine
                    +Row
                    +Colunm
                    +CurrentTurn
                    +EnterCoordinateToPut
                    +EnterOriginCoordinateToMove
                    +EnterTargetCoordinateToMove
                    +Error
                    +WinnerMessage
                    +Resume
                    +Goodbye
                    +GetToString(Message) : string
                    +Write(Message)
                    +WriteLine(Message)
                    +WriteLine(Message, title)
                }

                enum Error{
                    ~SquareIsOutOfRange
                    ~SquareIsOccupied
                    ~SquareIsEmpty
                    ~TokenIsNotOfCurrentPlayer
                    ~SquareCannotBeSameCoordinate
                    ~Null
                    ~IsNull(Error) : boolean
                    ~WriteLine(Error)
                }

                enum Token{
                    ~X
                    ~O
                    ~Null
                    ~GetToString() : String
                }
            }

            namespace ConsoleIOs{
                class ConsoleIO{
                }
                ConsoleIO <.up. Enums.Message
                ConsoleIO <.up. Enums.Error
            }
        }
    }
@enduml