@startuml Implementation View
    package "  " as TicTacToe.ConsoleApp {
    }

    package "  " as System.IO {
    }    

    [TicTacToe.exe] as exe

    exe *--> TicTacToe.ConsoleApp
    exe *--> System.IO
@enduml

