@startuml Domain Model
   
    TicTacToe *--> Board
    TicTacToe *--> Turn
    TicTacToe *--> "2" Player

    Turn "exchange" --> "2" Player

    Board *--> "3x3" Square
    Square o--> "0..1" Token
    Square *--> Coordinate

    Player -right-> Board
    Player *--> "3" Token
    Player *--> Color
    Player "has" ..> Goal

    Color <|-- X
    Color <|-- O
    Token *--> Color

    Goal <|-- Row
    Goal <|-- Colunm
    Goal <|-- MainDiagonal
    Goal <|-- InversedDiagonal
    Goal "need" ..> "3" Token
    Goal ..> Action : make

    Action ..> Square : target
    Action ..> "1" Token : need
    Action <|-- Put
    Action <|-- Move
    Move ..> Square : origin

@enduml